import type { Metadata } from "next";
import "./globals.css";
import Header from "./header/page";
import { StudentContextProvider } from "./contexts/student-context";
import Footer from "./footer/page";
import { UtilsObjectContextProvider } from "./contexts/utils_context";
import { AuthContextProvider } from "./contexts/auth-context";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full">
			<body className="flex flex-row justify-center items-center h-full bg-background text-textprimary">
				<AuthContextProvider>
					<UtilsObjectContextProvider>
						<StudentContextProvider>
								<div className="flex flex-col h-full py-5 w-full max-w-7xl">
									<Header />
									<div className={`bg-surface flex-grow overflow-y-auto`}>
										{children}
									</div>
									<Footer />
								</div>
							</StudentContextProvider>
					</UtilsObjectContextProvider>
				</AuthContextProvider>
			</body>
		</html>
	);
}
