import type { Metadata } from "next";
import "./globals.css";
import Header from "./header/page";
import { StudentContextProvider } from "./contexts/student-context";
import Footer from "./footer/page";
import { UtilsObjectContextProvider } from "./contexts/utils_context";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="flex flex-row justify-center items-center h-screen bg-background text-textprimary">
				<UtilsObjectContextProvider>
					<StudentContextProvider>
							<div>
								<Header />
								<div className={`bg-surface h-2/3 overflow-y-auto`}>
									{children}
								</div>
								<Footer />
							</div>
						</StudentContextProvider>
				</UtilsObjectContextProvider>
			</body>
		</html>
	);
}
